### ISSUE TITLE
Question: Why are requests queued?

### ISSUE THREAD

**Issue by franzliedke** [jgraichen/acfs#33]
Interesting project you have there. =)

When reading through the README, I stumbled across this part:

```ruby
Acfs.run # This call will fire all request as parallel as possible.
         # The sequence above would look similar to:
         #
         # Start                Fin
         #   |===================|       `Acfs.run`
         #   |====|                      /users/5
         #   |    |==============|       /comments?user=5
         #   |    |======|               /users/1
         #   |    |=======|              /users/4
         #   |    |======|               /users/10
```

Why are these requests queued until `Acfs.run` is executed? Can't you just start them right away and then simply have an `Acfs.wait` call that blocks until all requests are completed?

**Comment by jgraichen** [comment]
The primary reason is the underlying HTTP library [typhoeus](https://github.com/typhoeus/typhoeus) - one of the few libraries supporting parallel and pipelines requests at all. It requires to first queue requests and call `Hydra.run` to pass all requests to libcurl. This blocking call and invoke callbacks serial in the current thread (which is important for Rails, ActiveRecord, etc.) and raise errors. 

There is some kind of successor for acfs called [restify](https://github.com/jgraichen/restify) following hypermedia principles. It is based on [obligation](https://github.com/jgraichen/obligation) providing a Future (Java) and Promise (JS) style handling of requests. But the obligation library also has some quirk callback/waiting/blocking to ensure blocks are invoke in current thread as most of the ruby world is made for serial execution and the old-fashioned thread model. It's far harder than in languages promoting or enforcing another style of concurrency (e.g. functional languages like Erlang or Haskell or JavaScript being evented only).

There were some plans on changing acfs to a promise-like API but they were never implemented in favor of restify. I'm always open for suggestions and improvements but currently focus on restify and alternative transport stacks like (HTTP over) [ZeroMQ](http://zeromq.org/).

Does this answer your question?

**Comment by franzliedke** [comment]
It does, and very thoroughly. Thanks a lot!
