### ISSUE TITLE
Existence query method

### ISSUE THREAD

**Issue by franzliedke** [jgraichen/acfs#35]
How about an `exists?` method similar to that of [Rails' Active Record component](http://apidock.com/rails/ActiveRecord/Base/exists%3F/class)?

**Comment by jgraichen** [comment]
How should `exist?` behave? Should it just check if `all`/`where` returns a non-empty array? Should it try `/<resource>/<id>` for an error?

Acfs is not a database adapter speaking (more or less) standardized SQL. It is talking with a JSON HTTP API. There isn't much it can assume to exist, it all depends on the actual API. Any idea?

**Comment by franzliedke** [comment]
I have to admit that I don't know too much about the structure of Acfs.

My idea was something along the lines of first executing whatever Acfs does for a `find` query, and then return `true` for HTTP 2** responses and `false` for 4** responses. Would that be possible? If so, I can try to dig into the source code and send a PR. ;)

**Comment by jgraichen** [comment]
This may work but will only allow to check the existence by ID. You could not use filters defined on the list operation e.g. `exist?(published: true)`.

**Comment by franzliedke** [comment]
I know too little about Acfs, so I might have made some false assumptions. Feel free to close this if it doesn't seem feasible to you.

**Comment by jgraichen** [comment]
Acfs would - in any way - not return `true` and `false` as it would have to do a synchronized request in this case but return it via callback. In this case I think it's feasible to do it manually depending on the HTTP API your talking about e.g.

```ruby
Resource.where(param: 5, per_page: 1) {|items| @empty = items.empty? }
```
